import { describe, expect, it, vi } from 'vitest'
import type { Settings } from '../src/shared/types'

vi.mock('electron', () => ({ app: { getPath: () => 'C:\\SnagTest' } }))

import { sanitizeSettings } from '../src/main/settings'

// Mirrors the shipped defaults with every field customized to a valid,
// non-default value, so pass-through and fallback are distinguishable.
const valid: Settings = {
  defaultSaveDir: 'D:\\Media',
  speedLimit: { enabled: true, value: 750, unit: 'K' },
  concurrentFragments: 8,
  parallelDownloads: 3,
  filenameTemplate: '%(title)s [%(id)s]',
  notificationsEnabled: false,
  subtitles: { enabled: true, languages: ['de', 'fr'], embed: false, autoGenerated: true },
  preferredVideoContainer: 'mkv',
  preferredAudioFormat: 'flac',
  rememberLastChoices: false,
  lastKind: 'audio',
  ytdlpPath: 'C:\\Tools\\yt-dlp.exe',
  embedThumbnail: false,
  embedMetadata: false,
  browserHandoff: 'main',
  browserExtensionPromptDismissed: true,
  browserExtensionLastSeen: 1700000000000,
  runInBackground: false,
  launchAtLogin: true,
  bestQualityMode: false,
  multiAudio: { enabled: true, languages: ['ja'] },
  autoCheckUpdates: false,
  lastUpdateCheck: 1700000000001
}

describe('sanitizeSettings', () => {
  it('passes a fully valid settings object through unchanged', () => {
    expect(sanitizeSettings(valid)).toEqual(valid)
  })

  it('falls back to defaults entirely for non-object input', () => {
    for (const junk of [null, undefined, 'text', 42, true, ['array']]) {
      const result = sanitizeSettings(junk)
      expect(result.parallelDownloads).toBe(1)
      expect(result.speedLimit).toEqual({ enabled: false, value: 5, unit: 'M' })
      expect(result.preferredVideoContainer).toBe('mp4')
    }
  })

  it('rejects wrong-typed numbers that would break the download queue', () => {
    const result = sanitizeSettings({ ...valid, parallelDownloads: '3' })
    expect(result.parallelDownloads).toBe(1)
    expect(sanitizeSettings({ ...valid, parallelDownloads: null }).parallelDownloads).toBe(1)
    expect(sanitizeSettings({ ...valid, parallelDownloads: NaN }).parallelDownloads).toBe(1)
    expect(sanitizeSettings({ ...valid, concurrentFragments: 'lots' }).concurrentFragments).toBe(4)
    expect(sanitizeSettings({ ...valid, lastUpdateCheck: 'yesterday' }).lastUpdateCheck).toBe(0)
    expect(sanitizeSettings({ ...valid, browserExtensionLastSeen: {} }).browserExtensionLastSeen).toBe(0)
  })

  it('clamps out-of-range numbers into valid ranges', () => {
    expect(sanitizeSettings({ ...valid, parallelDownloads: 99 }).parallelDownloads).toBe(4)
    expect(sanitizeSettings({ ...valid, parallelDownloads: 0 }).parallelDownloads).toBe(1)
    expect(sanitizeSettings({ ...valid, parallelDownloads: 2.7 }).parallelDownloads).toBe(3)
    expect(sanitizeSettings({ ...valid, concurrentFragments: 64 }).concurrentFragments).toBe(16)
    expect(sanitizeSettings({ ...valid, concurrentFragments: -1 }).concurrentFragments).toBe(1)
    expect(sanitizeSettings({ ...valid, lastUpdateCheck: -5 }).lastUpdateCheck).toBe(0)
  })

  it('rejects wrong-typed booleans and strings', () => {
    expect(sanitizeSettings({ ...valid, notificationsEnabled: 'yes' }).notificationsEnabled).toBe(true)
    expect(sanitizeSettings({ ...valid, runInBackground: 1 }).runInBackground).toBe(true)
    expect(sanitizeSettings({ ...valid, launchAtLogin: 'true' }).launchAtLogin).toBe(false)
    expect(sanitizeSettings({ ...valid, filenameTemplate: 7 }).filenameTemplate).toBe('%(title)s')
    expect(sanitizeSettings({ ...valid, defaultSaveDir: '' }).defaultSaveDir).toBe('C:\\SnagTest')
    expect(sanitizeSettings({ ...valid, ytdlpPath: 123 }).ytdlpPath).toBeNull()
    expect(sanitizeSettings({ ...valid, ytdlpPath: null }).ytdlpPath).toBeNull()
  })

  it('rejects values outside the enum literal sets', () => {
    expect(sanitizeSettings({ ...valid, preferredVideoContainer: 'avi' }).preferredVideoContainer).toBe('mp4')
    expect(sanitizeSettings({ ...valid, preferredAudioFormat: 'ogg' }).preferredAudioFormat).toBe('mp3')
    expect(sanitizeSettings({ ...valid, lastKind: 'playlist' }).lastKind).toBe('video')
    expect(sanitizeSettings({ ...valid, browserHandoff: 'popup' }).browserHandoff).toBe('quick')
  })

  it('validates nested speedLimit per field so a bad unit cannot poison --limit-rate', () => {
    const result = sanitizeSettings({
      ...valid,
      speedLimit: { enabled: 'on', value: '5', unit: 'G' }
    })
    expect(result.speedLimit).toEqual({ enabled: false, value: 5, unit: 'M' })

    // A partially valid nested object keeps the good fields.
    const partial = sanitizeSettings({ ...valid, speedLimit: { enabled: true, value: 2, unit: 'X' } })
    expect(partial.speedLimit).toEqual({ enabled: true, value: 2, unit: 'M' })
  })

  it('validates nested subtitles and multiAudio per field', () => {
    const result = sanitizeSettings({
      ...valid,
      subtitles: { enabled: 1, languages: ['en', 42, ''], embed: 'no', autoGenerated: null },
      multiAudio: { enabled: 'yes', languages: 'en' }
    })
    expect(result.subtitles).toEqual({ enabled: false, languages: ['en'], embed: true, autoGenerated: false })
    expect(result.multiAudio).toEqual({ enabled: false, languages: [] })

    // Empty or filtered-empty lists are valid: users can disable all language favorites.
    expect(sanitizeSettings({ ...valid, multiAudio: { enabled: true, languages: [7, ''] } }).multiAudio)
      .toEqual({ enabled: true, languages: [] })
    expect(sanitizeSettings({ ...valid, subtitles: { ...valid.subtitles, languages: [] } }).subtitles.languages)
      .toEqual([])
  })

  it('drops unknown keys from hand-edited files', () => {
    const result = sanitizeSettings({ ...valid, legacyOption: true, hacker: '--exec rm' })
    expect(result).toEqual(valid)
    expect('legacyOption' in result).toBe(false)
    expect('hacker' in result).toBe(false)
  })
})
