import { app } from 'electron'
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import {
  AUDIO_OUTPUT_FORMATS,
  BROWSER_HANDOFFS,
  DOWNLOAD_KINDS,
  SPEED_LIMIT_UNITS,
  VIDEO_CONTAINERS
} from '@shared/types'
import type { Settings } from '@shared/types'

function defaultSettings(): Settings {
  let downloads: string
  try {
    downloads = app.getPath('downloads')
  } catch {
    downloads = app.getPath('home')
  }
  return {
    defaultSaveDir: downloads,
    speedLimit: { enabled: false, value: 5, unit: 'M' },
    concurrentFragments: 4,
    parallelDownloads: 1,
    filenameTemplate: '%(title)s',
    notificationsEnabled: true,
    subtitles: { enabled: false, languages: ['en'], embed: true, autoGenerated: false },
    preferredVideoContainer: 'mp4',
    preferredAudioFormat: 'mp3',
    rememberLastChoices: true,
    lastKind: 'video',
    ytdlpPath: null,
    embedThumbnail: true,
    embedMetadata: true,
    browserHandoff: 'quick',
    browserExtensionPromptDismissed: false,
    browserExtensionLastSeen: 0,
    runInBackground: true,
    launchAtLogin: false,
    bestQualityMode: true,
    // An empty list marks a fresh install that has not chosen preferences yet.
    // Pickers still fall back to the video's default/English track.
    multiAudio: { enabled: false, languages: [] },
    autoCheckUpdates: true,
    lastUpdateCheck: 0
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value)
}

function clampNumber(value: unknown, min: number, max: number, fallback: number): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) return fallback
  return Math.max(min, Math.min(max, value))
}

function pickBoolean(value: unknown, fallback: boolean): boolean {
  return typeof value === 'boolean' ? value : fallback
}

function pickString(value: unknown, fallback: string): string {
  return typeof value === 'string' && value.length > 0 ? value : fallback
}

function pickEnum<T extends string>(value: unknown, allowed: readonly T[], fallback: T): T {
  return allowed.includes(value as T) ? (value as T) : fallback
}

function pickLanguages(value: unknown, fallback: string[]): string[] {
  if (!Array.isArray(value)) return fallback
  const langs = value.filter((v): v is string => typeof v === 'string' && v.length > 0)
  return langs
}

// Rebuild a trustworthy Settings object from whatever the JSON file contained.
// A hand-edited or corrupted settings.json must never leak wrong-typed values
// into yt-dlp arguments or the download queue, so every field is checked
// individually and falls back to its default (mirrors restoreJobs in downloader).
export function sanitizeSettings(raw: unknown): Settings {
  const defaults = defaultSettings()
  if (!isRecord(raw)) return defaults

  const speedLimit = isRecord(raw.speedLimit) ? raw.speedLimit : {}
  const subtitles = isRecord(raw.subtitles) ? raw.subtitles : {}
  const multiAudio = isRecord(raw.multiAudio) ? raw.multiAudio : {}

  return {
    defaultSaveDir: pickString(raw.defaultSaveDir, defaults.defaultSaveDir),
    speedLimit: {
      enabled: pickBoolean(speedLimit.enabled, defaults.speedLimit.enabled),
      value: clampNumber(speedLimit.value, 1, 9999, defaults.speedLimit.value),
      unit: pickEnum(speedLimit.unit, SPEED_LIMIT_UNITS, defaults.speedLimit.unit)
    },
    concurrentFragments: Math.round(
      clampNumber(raw.concurrentFragments, 1, 16, defaults.concurrentFragments)
    ),
    // The queue pump only ever runs 1–4 downloads at once.
    parallelDownloads: Math.round(
      clampNumber(raw.parallelDownloads, 1, 4, defaults.parallelDownloads)
    ),
    filenameTemplate: pickString(raw.filenameTemplate, defaults.filenameTemplate),
    notificationsEnabled: pickBoolean(raw.notificationsEnabled, defaults.notificationsEnabled),
    subtitles: {
      enabled: pickBoolean(subtitles.enabled, defaults.subtitles.enabled),
      languages: pickLanguages(subtitles.languages, defaults.subtitles.languages),
      embed: pickBoolean(subtitles.embed, defaults.subtitles.embed),
      autoGenerated: pickBoolean(subtitles.autoGenerated, defaults.subtitles.autoGenerated)
    },
    preferredVideoContainer: pickEnum(
      raw.preferredVideoContainer,
      VIDEO_CONTAINERS,
      defaults.preferredVideoContainer
    ),
    preferredAudioFormat: pickEnum(
      raw.preferredAudioFormat,
      AUDIO_OUTPUT_FORMATS,
      defaults.preferredAudioFormat
    ),
    rememberLastChoices: pickBoolean(raw.rememberLastChoices, defaults.rememberLastChoices),
    lastKind: pickEnum(raw.lastKind, DOWNLOAD_KINDS, defaults.lastKind),
    ytdlpPath: typeof raw.ytdlpPath === 'string' && raw.ytdlpPath.length > 0 ? raw.ytdlpPath : null,
    embedThumbnail: pickBoolean(raw.embedThumbnail, defaults.embedThumbnail),
    embedMetadata: pickBoolean(raw.embedMetadata, defaults.embedMetadata),
    browserHandoff: pickEnum(raw.browserHandoff, BROWSER_HANDOFFS, defaults.browserHandoff),
    browserExtensionPromptDismissed: pickBoolean(
      raw.browserExtensionPromptDismissed,
      defaults.browserExtensionPromptDismissed
    ),
    browserExtensionLastSeen: clampNumber(
      raw.browserExtensionLastSeen,
      0,
      Number.MAX_SAFE_INTEGER,
      defaults.browserExtensionLastSeen
    ),
    runInBackground: pickBoolean(raw.runInBackground, defaults.runInBackground),
    launchAtLogin: pickBoolean(raw.launchAtLogin, defaults.launchAtLogin),
    bestQualityMode: pickBoolean(raw.bestQualityMode, defaults.bestQualityMode),
    multiAudio: {
      enabled: pickBoolean(multiAudio.enabled, defaults.multiAudio.enabled),
      languages: pickLanguages(multiAudio.languages, defaults.multiAudio.languages)
    },
    autoCheckUpdates: pickBoolean(raw.autoCheckUpdates, defaults.autoCheckUpdates),
    lastUpdateCheck: clampNumber(
      raw.lastUpdateCheck,
      0,
      Number.MAX_SAFE_INTEGER,
      defaults.lastUpdateCheck
    )
  }
}

let cache: Settings | null = null

function filePath(): string {
  return join(app.getPath('userData'), 'settings.json')
}

// Deep-ish merge that keeps nested defaults when the stored file predates a field.
function merge(base: Settings, stored: Partial<Settings>): Settings {
  return {
    ...base,
    ...stored,
    speedLimit: { ...base.speedLimit, ...(stored.speedLimit || {}) },
    subtitles: { ...base.subtitles, ...(stored.subtitles || {}) },
    multiAudio: { ...base.multiAudio, ...(stored.multiAudio || {}) }
  }
}

export function loadSettings(): Settings {
  if (cache) return cache
  try {
    const raw = readFileSync(filePath(), 'utf-8')
    cache = sanitizeSettings(JSON.parse(raw))
  } catch {
    cache = defaultSettings()
  }
  return cache
}

export function saveSettings(patch: Partial<Settings>): Settings {
  const current = loadSettings()
  const next = merge(current, patch)
  cache = next
  try {
    const p = filePath()
    if (!existsSync(dirname(p))) mkdirSync(dirname(p), { recursive: true })
    writeFileSync(p, JSON.stringify(next, null, 2), 'utf-8')
  } catch (err) {
    console.error('Failed to persist settings:', err)
  }
  return next
}
